import sys

import env
import fsops
from sources import Sources

"""
CLI
"""
verbose = GetOption("verbose")
no_clang_format = GetOption("no_clang_format")
no_unit_test = GetOption("no_unit_test")
test_output = GetOption("test_output")
timeout = GetOption("timeout")


"""
Imports
"""
Import("project_dirnode")


"""
Define file nodes and directory nodes
"""
PROJECT_DIR = project_dirnode
FREERTOS_SOURCE_POSIX_SOURCE_DIR = PROJECT_DIR.Dir("freertos_source")
FREERTOS_SOURCE_COMMON = Dir("#/projects/lpc40xx_freertos/l1_freertos")

""" Build artifact nodes """
VARIANT_DIR = Dir("#/_build_{}".format(PROJECT_DIR.name))
OBJ_DIR = VARIANT_DIR.Dir("obj")
UNIT_TEST_BUILD_DIR = VARIANT_DIR.Dir("test")

"""
Import build environment
"""
env_x86 = env.register_environment("env_x86")

""" Add/modify additional parameters """
env_x86 = env_x86.Clone(
    tools=["clangformat"]
)

""" Source and include nodes """
INCLUDE_DIRS = [
    FREERTOS_SOURCE_COMMON.Dir("include"),
    FREERTOS_SOURCE_COMMON.Dir("customized_code"),
    FREERTOS_SOURCE_COMMON.Dir("mem_mang"),
]

EXCLUDED_SRC_FILES = [
]

env_x86.VariantDir(variant_dir=VARIANT_DIR, src_dir=Dir("."), duplicate=0)


"""
Search and group files to build
"""
sources = fsops.scan_tree(project_dirnode)
sources += fsops.scan_tree(FREERTOS_SOURCE_COMMON.Dir("source"))
sources += fsops.scan_tree(FREERTOS_SOURCE_COMMON.Dir("mem_mang"))
sources.source_filenodes,_ = fsops.filter_files(sources.source_filenodes, EXCLUDED_SRC_FILES)

env_x86["CPPPATH"].extend(INCLUDE_DIRS)
env_x86["CPPPATH"].extend(sources.include_dirnodes)


"""
Perform builds
"""

""" Compile all sources -> objects """
obj_filenodes = []
for filenode in sources.source_filenodes + sources.assembly_filenodes:
    dest_filepath = fsops.ch_target_filenode(filenode, OBJ_DIR, "o")
    new_obj_filenodes = env_x86.Object(target=dest_filepath, source=filenode)
    obj_filenodes.extend(new_obj_filenodes)

exe_filenodes = env_x86.Program(target=VARIANT_DIR.File("{}.exe".format(PROJECT_DIR.name)), source=obj_filenodes)

"""
Automatically format all files
"""
if not no_clang_format:
    exclude_file_patterns = [
        "FreeRTOSConfig.h",
    ]

    exclude_dir_patterns = [
        "freertos_source", # POSIX code
        "l1_freertos",     # This is for '#/projects/lpc40xx_freertos/l1_freertos'
    ]

    format_filenodes, _ = fsops.filter_files(
        filenodes=sources.formattable_filenodes,
        exclude_filename_patterns=exclude_file_patterns,
        exclude_dirname_patterns=exclude_dir_patterns,
    )
    for filenode in format_filenodes:
        env_x86.ClangFormat(filenode=filenode, verbose=verbose)

"""
Run unit tests
"""
if not no_unit_test:
    unit_test_results = env_x86.Test(
        source=sources.unit_test_filenodes,
        target=UNIT_TEST_BUILD_DIR,
        sources=sources,
        summary_only=not test_output,
        timeout=timeout,
        verbose=verbose,
    )
    Requires(obj_filenodes, unit_test_results)
